// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

export interface Host {
    "id": string;
    "name": string;
    "hostname": string;
    "port": number;
    "username": string;
    "authMethod": string;
    "keyId": string;
    "groupId": string;
    "color": string;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;
    "deletedAt"?: time$0.Time | null;
}

export interface HostCreateInput {
    "name": string;
    "hostname": string;
    "port": number;
    "username": string;
    "authMethod": string;
    "password"?: string;
    "keyId": string;
    "groupId": string;
    "color": string;
}

export interface HostGroup {
    "id": string;
    "name": string;
    "parentId": string;
    "sortOrder": number;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;
}

export interface HostGroupCreateInput {
    "name": string;
    "parentId": string;
}

export interface HostGroupUpdateInput {
    "id": string;
    "name"?: string | null;
    "parentId"?: string | null;
}

export interface HostUpdateInput {
    "id": string;
    "name"?: string | null;
    "hostname"?: string | null;
    "port"?: number | null;
    "username"?: string | null;
    "authMethod"?: string | null;
    "password"?: string | null;
    "keyId"?: string | null;
    "groupId"?: string | null;
    "color"?: string | null;
}

export interface Key {
    "id": string;
    "name": string;
    "publicKey": string;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;
}

export interface KeyCreateInput {
    "name": string;
    "privateKey": string;
    "publicKey"?: string;
    "passphrase"?: string;
}

export interface KeyUpdateInput {
    "id": string;
    "name"?: string | null;
    "privateKey"?: string | null;
    "publicKey"?: string | null;
    "passphrase"?: string | null;
}

export interface PortForward {
    "id": string;
    "name": string;
    "hostId": string;
    "type": string;
    "localAddress": string;
    "localPort": number;
    "remoteHost": string;
    "remotePort": number;
    "socksHost": string;
    "socksPort": number;
    "enabled": boolean;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;
}

export interface PortForwardCreateInput {
    "name": string;
    "hostId": string;
    "type": string;
    "localAddress"?: string;
    "localPort"?: number;
    "remoteHost"?: string;
    "remotePort"?: number;
    "socksHost"?: string;
    "socksPort"?: number;
}

export interface PortForwardUpdateInput {
    "id": string;
    "name"?: string | null;
    "hostId"?: string | null;
    "type"?: string | null;
    "localAddress"?: string | null;
    "localPort"?: number | null;
    "remoteHost"?: string | null;
    "remotePort"?: number | null;
    "socksHost"?: string | null;
    "socksPort"?: number | null;
}

export interface Snippet {
    "id": string;
    "name": string;
    "content": string;
    "language": string;
    "folderId": string;
    "sortOrder": number;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;
}

export interface SnippetCreateInput {
    "name": string;
    "content": string;
    "language": string;
    "folderId": string;
}

export interface SnippetFolder {
    "id": string;
    "name": string;
    "parentId": string;
    "sortOrder": number;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;
}

export interface SnippetFolderCreateInput {
    "name": string;
    "parentId": string;
}

export interface SnippetFolderUpdateInput {
    "id": string;
    "name"?: string | null;
    "parentId"?: string | null;
}

export interface SnippetUpdateInput {
    "id": string;
    "name"?: string | null;
    "content"?: string | null;
    "language"?: string | null;
    "folderId"?: string | null;
}
