ALTER TABLE ydsterm_hosts ADD COLUMN sync_user TEXT NOT NULL DEFAULT 'LOCALUSER';
ALTER TABLE ydsterm_host_groups ADD COLUMN sync_user TEXT NOT NULL DEFAULT 'LOCALUSER';
ALTER TABLE ydsterm_keys ADD COLUMN sync_user TEXT NOT NULL DEFAULT 'LOCALUSER';
ALTER TABLE ydsterm_snippets ADD COLUMN sync_user TEXT NOT NULL DEFAULT 'LOCALUSER';
ALTER TABLE ydsterm_snippet_folders ADD COLUMN sync_user TEXT NOT NULL DEFAULT 'LOCALUSER';
ALTER TABLE ydsterm_port_forwards ADD COLUMN sync_user TEXT NOT NULL DEFAULT 'LOCALUSER';

CREATE TABLE IF NOT EXISTS ydsterm_sync_users (
    id TEXT PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    is_active INTEGER DEFAULT 0,
    last_sync_at DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ydsterm_settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

INSERT OR IGNORE INTO ydsterm_sync_users (id, username, is_active) VALUES ('0000000000LOCALUSER0', 'LOCALUSER', 1);
