// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

export function Create(input: types$0.HostCreateInput): $CancellablePromise<types$0.Host | null> {
    return $Call.ByID(2739018442, input);
}

export function CreateGroup(input: types$0.HostGroupCreateInput): $CancellablePromise<types$0.HostGroup | null> {
    return $Call.ByID(2138392733, input);
}

export function CreateKey(input: types$0.KeyCreateInput): $CancellablePromise<types$0.Key | null> {
    return $Call.ByID(3334554209, input);
}

export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(2054530745, id);
}

export function DeleteGroup(id: string): $CancellablePromise<void> {
    return $Call.ByID(1621986832, id);
}

export function DeleteKey(id: string): $CancellablePromise<void> {
    return $Call.ByID(2980658224, id);
}

export function Get(id: string): $CancellablePromise<types$0.Host | null> {
    return $Call.ByID(2152930074, id);
}

export function GetKey(id: string): $CancellablePromise<types$0.Key | null> {
    return $Call.ByID(3912140401, id);
}

export function List(groupID: string): $CancellablePromise<types$0.Host[] | null> {
    return $Call.ByID(3870224442, groupID);
}

export function ListGroups(): $CancellablePromise<types$0.HostGroup[] | null> {
    return $Call.ByID(2779166554);
}

export function ListKeys(): $CancellablePromise<types$0.Key[] | null> {
    return $Call.ByID(2925992454);
}

export function Update(input: types$0.HostUpdateInput): $CancellablePromise<types$0.Host | null> {
    return $Call.ByID(234660439, input);
}

export function UpdateGroup(input: types$0.HostGroupUpdateInput): $CancellablePromise<types$0.HostGroup | null> {
    return $Call.ByID(3164398014, input);
}

export function UpdateKey(input: types$0.KeyUpdateInput): $CancellablePromise<types$0.Key | null> {
    return $Call.ByID(2976585582, input);
}
