// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface FileEntry {
    "name": string;
    "path": string;
    "isDir": boolean;
    "size": number;
    "mode": string;
    "modTime": string;
}

export interface SftpTransferPayload {
    "TransferId": string;
    "BytesDone": number;
    "BytesTotal": number;
    "Done": boolean;
    "Err": string;
}

export interface TermDisconnectedPayload {
    "SessionId": string;
}

/**
 * Wails v3 events: field names MUST match the JavaScript property names exactly.
 * JSON tags may be ignored by Wails internal serialization.
 */
export interface TermOutputPayload {
    "SessionId": string;
    "Data": string;
    "IsStderr": boolean;
}
