// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

export function Create(input: types$0.PortForwardCreateInput): $CancellablePromise<types$0.PortForward | null> {
    return $Call.ByID(19113078, input);
}

export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(257449597, id);
}

export function Get(id: string): $CancellablePromise<types$0.PortForward | null> {
    return $Call.ByID(3167283502, id);
}

export function List(hostID: string): $CancellablePromise<types$0.PortForward[] | null> {
    return $Call.ByID(3362430782, hostID);
}

export function Toggle(id: string, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(2993566010, id, enabled);
}

export function Update(input: types$0.PortForwardUpdateInput): $CancellablePromise<types$0.PortForward | null> {
    return $Call.ByID(3760381851, input);
}
