// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function BaseName(p: string, isLocal: boolean): $CancellablePromise<string> {
    return $Call.ByID(2560004467, p, isLocal);
}

export function CancelTransfer(transferId: string): $CancellablePromise<void> {
    return $Call.ByID(861436792, transferId);
}

export function Connect(hostID: string): $CancellablePromise<string> {
    return $Call.ByID(3081442993, hostID);
}

export function Delete(sessionID: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(1025957842, sessionID, path);
}

export function DeleteLocal(path: string): $CancellablePromise<void> {
    return $Call.ByID(3313932201, path);
}

export function Disconnect(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(1921623267, sessionID);
}

export function Download(sessionID: string, path: string): $CancellablePromise<string> {
    return $Call.ByID(2014649169, sessionID, path);
}

export function DownloadFile(sessionID: string, remotePath: string, localPath: string, transferId: string): $CancellablePromise<void> {
    return $Call.ByID(2498075831, sessionID, remotePath, localPath, transferId);
}

export function HomeDir(sessionID: string): $CancellablePromise<string> {
    return $Call.ByID(2608661453, sessionID);
}

export function HomeLocal(): $CancellablePromise<string> {
    return $Call.ByID(3116190365);
}

export function List(sessionID: string, path: string): $CancellablePromise<$models.FileEntry[] | null> {
    return $Call.ByID(1421097049, sessionID, path);
}

export function ListLocal(path: string): $CancellablePromise<$models.FileEntry[] | null> {
    return $Call.ByID(1092708396, path);
}

export function Mkdir(sessionID: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(987587504, sessionID, path);
}

export function MkdirLocal(path: string): $CancellablePromise<void> {
    return $Call.ByID(2189462763, path);
}

export function ParentDir(p: string, isLocal: boolean): $CancellablePromise<string> {
    return $Call.ByID(1578978612, p, isLocal);
}

export function ReadLocal(path: string): $CancellablePromise<string> {
    return $Call.ByID(3327808352, path);
}

export function Rename(sessionID: string, oldPath: string, newPath: string): $CancellablePromise<void> {
    return $Call.ByID(3186375307, sessionID, oldPath, newPath);
}

export function RenameLocal(oldPath: string, newPath: string): $CancellablePromise<void> {
    return $Call.ByID(3652120986, oldPath, newPath);
}

export function Upload(sessionID: string, path: string, encoded: string): $CancellablePromise<void> {
    return $Call.ByID(3804706164, sessionID, path, encoded);
}

export function UploadFile(sessionID: string, localPath: string, remotePath: string, transferId: string): $CancellablePromise<void> {
    return $Call.ByID(2293034722, sessionID, localPath, remotePath, transferId);
}

export function WriteLocal(path: string, encoded: string): $CancellablePromise<void> {
    return $Call.ByID(1131933983, path, encoded);
}
