// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

export function Create(input: types$0.SnippetCreateInput): $CancellablePromise<types$0.Snippet | null> {
    return $Call.ByID(4056966151, input);
}

export function CreateFolder(input: types$0.SnippetFolderCreateInput): $CancellablePromise<types$0.SnippetFolder | null> {
    return $Call.ByID(3682603411, input);
}

export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(572922300, id);
}

export function DeleteFolder(id: string): $CancellablePromise<void> {
    return $Call.ByID(1553507656, id);
}

export function Get(id: string): $CancellablePromise<types$0.Snippet | null> {
    return $Call.ByID(815199865, id);
}

export function List(folderID: string): $CancellablePromise<types$0.Snippet[] | null> {
    return $Call.ByID(3097566759, folderID);
}

export function ListFolders(): $CancellablePromise<types$0.SnippetFolder[] | null> {
    return $Call.ByID(3983545088);
}

export function Update(input: types$0.SnippetUpdateInput): $CancellablePromise<types$0.Snippet | null> {
    return $Call.ByID(3558121870, input);
}

export function UpdateFolder(input: types$0.SnippetFolderUpdateInput): $CancellablePromise<types$0.SnippetFolder | null> {
    return $Call.ByID(1980033214, input);
}
