// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * Connect opens an SSH connection + PTY, returns a session ID.
 */
export function Connect(hostID: string): $CancellablePromise<string> {
    return $Call.ByID(3087046514, hostID);
}

/**
 * Disconnect tears down the SSH session.
 */
export function Disconnect(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(3498855414, sessionID);
}

/**
 * ListSessions returns metadata for active sessions.
 */
export function ListSessions(): $CancellablePromise<({ [_ in string]?: any } | null)[] | null> {
    return $Call.ByID(249670281);
}

/**
 * Resize adjusts the PTY window.
 */
export function Resize(sessionID: string, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(2723754068, sessionID, cols, rows);
}

/**
 * Write sends user input to the remote PTY.
 */
export function Write(sessionID: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(2218670411, sessionID, data);
}
