// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"context"

	"ydsterm/internal/dbcore/dao/internal"
	"ydsterm/internal/dbcore/model/entity"
	"ydsterm/internal/types"
)

type ydstermPortForwardsDao struct {
	*internal.YdstermPortForwardsDao
}

var (
	YdstermPortForwards = ydstermPortForwardsDao{internal.NewYdstermPortForwardsDao()}
)

func (d *ydstermPortForwardsDao) Create(ctx context.Context, input types.PortForwardCreateInput) (*entity.YdstermPortForwards, error) {
	id := types.NewID()
	_, err := d.Ctx(ctx).Data(map[string]interface{}{
		d.Columns().Id:           id,
		d.Columns().Name:         input.Name,
		d.Columns().HostId:       input.HostID,
		d.Columns().Type:         input.Type,
		d.Columns().LocalAddress: input.LocalAddress,
		d.Columns().LocalPort:    input.LocalPort,
		d.Columns().RemoteHost:   input.RemoteHost,
		d.Columns().RemotePort:   input.RemotePort,
		d.Columns().SocksHost:    input.SocksHost,
		d.Columns().SocksPort:    input.SocksPort,
		d.Columns().Enabled:      0,
	}).Insert()
	if err != nil {
		return nil, err
	}
	var pf *entity.YdstermPortForwards
	err = d.Ctx(ctx).WherePri(id).Scan(&pf)
	return pf, err
}

func (d *ydstermPortForwardsDao) Update(ctx context.Context, id string, data map[string]interface{}) error {
	if len(data) == 0 {
		return nil
	}
	_, err := d.Ctx(ctx).WherePri(id).Update(data)
	return err
}

func (d *ydstermPortForwardsDao) Delete(ctx context.Context, id string) error {
	_, err := d.Ctx(ctx).WherePri(id).Delete()
	return err
}

func (d *ydstermPortForwardsDao) Get(ctx context.Context, id string) (*entity.YdstermPortForwards, error) {
	var pf *entity.YdstermPortForwards
	err := d.Ctx(ctx).WherePri(id).Scan(&pf)
	return pf, err
}

func (d *ydstermPortForwardsDao) List(ctx context.Context, hostID string) ([]entity.YdstermPortForwards, error) {
	m := d.Ctx(ctx)
	if hostID != "" {
		m = m.Where(d.Columns().HostId, hostID)
	}
	var pfs []entity.YdstermPortForwards
	err := m.OrderAsc(d.Columns().Name).Scan(&pfs)
	if err != nil {
		return nil, err
	}
	if pfs == nil {
		pfs = []entity.YdstermPortForwards{}
	}
	return pfs, nil
}

func (d *ydstermPortForwardsDao) Toggle(ctx context.Context, id string, enabled bool) error {
	val := 0
	if enabled {
		val = 1
	}
	_, err := d.Ctx(ctx).WherePri(id).Update(map[string]interface{}{
		d.Columns().Enabled: val,
	})
	return err
}
