// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ydsterm/internal/dbcore/dao/internal"
)

// ydstermSchemaMigrationsDao is the data access object for the table ydsterm_schema_migrations.
// You can define custom methods on it to extend its functionality as needed.
type ydstermSchemaMigrationsDao struct {
	*internal.YdstermSchemaMigrationsDao
}

var (
	// YdstermSchemaMigrations is a globally accessible object for table ydsterm_schema_migrations operations.
	YdstermSchemaMigrations = ydstermSchemaMigrationsDao{internal.NewYdstermSchemaMigrationsDao()}
)

// Add your custom methods and functionality below.
