// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"context"

	"ydsterm/internal/dbcore/dao/internal"
	"ydsterm/internal/dbcore/model/entity"
	"ydsterm/internal/types"
)

type ydstermSnippetFoldersDao struct {
	*internal.YdstermSnippetFoldersDao
}

var (
	YdstermSnippetFolders = ydstermSnippetFoldersDao{internal.NewYdstermSnippetFoldersDao()}
)

func (d *ydstermSnippetFoldersDao) Create(ctx context.Context, input types.SnippetFolderCreateInput) (*entity.YdstermSnippetFolders, error) {
	id := types.NewID()
	_, err := d.Ctx(ctx).Data(map[string]interface{}{
		d.Columns().Id:       id,
		d.Columns().Name:     input.Name,
		d.Columns().ParentId: input.ParentID,
	}).Insert()
	if err != nil {
		return nil, err
	}
	var f *entity.YdstermSnippetFolders
	err = d.Ctx(ctx).WherePri(id).Scan(&f)
	return f, err
}

func (d *ydstermSnippetFoldersDao) Update(ctx context.Context, id string, data map[string]interface{}) error {
	if len(data) == 0 {
		return nil
	}
	_, err := d.Ctx(ctx).WherePri(id).Update(data)
	return err
}

func (d *ydstermSnippetFoldersDao) Delete(ctx context.Context, id string) error {
	_, err := d.Ctx(ctx).WherePri(id).Delete()
	return err
}

func (d *ydstermSnippetFoldersDao) Get(ctx context.Context, id string) (*entity.YdstermSnippetFolders, error) {
	var f *entity.YdstermSnippetFolders
	err := d.Ctx(ctx).WherePri(id).Scan(&f)
	return f, err
}

func (d *ydstermSnippetFoldersDao) List(ctx context.Context) ([]entity.YdstermSnippetFolders, error) {
	var folders []entity.YdstermSnippetFolders
	err := d.Ctx(ctx).OrderAsc(d.Columns().SortOrder).OrderAsc(d.Columns().Name).Scan(&folders)
	if err != nil {
		return nil, err
	}
	if folders == nil {
		folders = []entity.YdstermSnippetFolders{}
	}
	return folders, nil
}
