// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"context"

	"ydsterm/internal/dbcore/dao/internal"
	"ydsterm/internal/dbcore/model/entity"
	"ydsterm/internal/types"
)

type ydstermHostGroupsDao struct {
	*internal.YdstermHostGroupsDao
}

var (
	YdstermHostGroups = ydstermHostGroupsDao{internal.NewYdstermHostGroupsDao()}
)

func (d *ydstermHostGroupsDao) Create(ctx context.Context, input types.HostGroupCreateInput) (*entity.YdstermHostGroups, error) {
	id := types.NewID()
	_, err := d.Ctx(ctx).Data(map[string]interface{}{
		d.Columns().Id:       id,
		d.Columns().Name:     input.Name,
		d.Columns().ParentId: input.ParentID,
	}).Insert()
	if err != nil {
		return nil, err
	}
	var g *entity.YdstermHostGroups
	err = d.Ctx(ctx).WherePri(id).Scan(&g)
	return g, err
}

func (d *ydstermHostGroupsDao) Update(ctx context.Context, id string, data map[string]interface{}) error {
	if len(data) == 0 {
		return nil
	}
	_, err := d.Ctx(ctx).WherePri(id).Update(data)
	return err
}

func (d *ydstermHostGroupsDao) Delete(ctx context.Context, id string) error {
	_, _ = YdstermHosts.Ctx(ctx).Data(map[string]interface{}{
		YdstermHosts.Columns().GroupId: "",
	}).Where(YdstermHosts.Columns().GroupId, id).Update()
	_, err := d.Ctx(ctx).WherePri(id).Delete()
	return err
}

func (d *ydstermHostGroupsDao) Get(ctx context.Context, id string) (*entity.YdstermHostGroups, error) {
	var g *entity.YdstermHostGroups
	err := d.Ctx(ctx).WherePri(id).Scan(&g)
	return g, err
}

func (d *ydstermHostGroupsDao) List(ctx context.Context) ([]entity.YdstermHostGroups, error) {
	var groups []entity.YdstermHostGroups
	err := d.Ctx(ctx).OrderAsc(d.Columns().SortOrder).OrderAsc(d.Columns().Name).Scan(&groups)
	if err != nil {
		return nil, err
	}
	if groups == nil {
		groups = []entity.YdstermHostGroups{}
	}
	return groups, nil
}
