// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"context"

	"ydsterm/internal/dbcore/dao/internal"
	"ydsterm/internal/dbcore/model/entity"
	"ydsterm/internal/types"
)

type ydstermKeysDao struct {
	*internal.YdstermKeysDao
}

var (
	YdstermKeys = ydstermKeysDao{internal.NewYdstermKeysDao()}
)

func (d *ydstermKeysDao) Create(ctx context.Context, input types.KeyCreateInput) (*entity.YdstermKeys, error) {
	id := types.NewID()
	_, err := d.Ctx(ctx).Data(map[string]interface{}{
		d.Columns().Id:            id,
		d.Columns().Name:          input.Name,
		d.Columns().PrivateKeyEnc: "", // encrypted by service
		d.Columns().PublicKey:     input.PublicKey,
		d.Columns().PassphraseEnc: "", // encrypted by service
	}).Insert()
	if err != nil {
		return nil, err
	}
	var key *entity.YdstermKeys
	err = d.Ctx(ctx).WherePri(id).Scan(&key)
	return key, err
}

func (d *ydstermKeysDao) Update(ctx context.Context, id string, data map[string]interface{}) error {
	if len(data) == 0 {
		return nil
	}
	_, err := d.Ctx(ctx).WherePri(id).Update(data)
	return err
}

func (d *ydstermKeysDao) Delete(ctx context.Context, id string) error {
	_, err := d.Ctx(ctx).WherePri(id).Delete()
	return err
}

func (d *ydstermKeysDao) Get(ctx context.Context, id string) (*entity.YdstermKeys, error) {
	var key *entity.YdstermKeys
	err := d.Ctx(ctx).WherePri(id).Scan(&key)
	return key, err
}

func (d *ydstermKeysDao) List(ctx context.Context) ([]entity.YdstermKeys, error) {
	var keys []entity.YdstermKeys
	err := d.Ctx(ctx).OrderAsc(d.Columns().Name).Scan(&keys)
	if err != nil {
		return nil, err
	}
	if keys == nil {
		keys = []entity.YdstermKeys{}
	}
	return keys, nil
}
