// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"context"

	"github.com/gogf/gf/v2/os/gtime"

	"ydsterm/internal/dbcore/dao/internal"
	"ydsterm/internal/dbcore/model/entity"
	"ydsterm/internal/types"
)

type ydstermHostsDao struct {
	*internal.YdstermHostsDao
}

var (
	YdstermHosts = ydstermHostsDao{internal.NewYdstermHostsDao()}
)

func (d *ydstermHostsDao) Create(ctx context.Context, input types.HostCreateInput) (*entity.YdstermHosts, error) {
	id := types.NewID()
	_, err := d.Ctx(ctx).Data(map[string]interface{}{
		d.Columns().Id:          id,
		d.Columns().Name:        input.Name,
		d.Columns().Hostname:    input.Hostname,
		d.Columns().Port:        input.Port,
		d.Columns().Username:    input.Username,
		d.Columns().AuthMethod:  input.AuthMethod,
		d.Columns().PasswordEnc: "", // encrypted separately by service
		d.Columns().KeyId:       input.KeyID,
		d.Columns().GroupId:     input.GroupID,
		d.Columns().Color:       input.Color,
	}).Insert()
	if err != nil {
		return nil, err
	}
	var host *entity.YdstermHosts
	err = d.Ctx(ctx).WherePri(id).Scan(&host)
	return host, err
}

func (d *ydstermHostsDao) Update(ctx context.Context, id string, data map[string]interface{}) error {
	if len(data) == 0 {
		return nil
	}
	_, err := d.Ctx(ctx).WherePri(id).Update(data)
	return err
}

func (d *ydstermHostsDao) Delete(ctx context.Context, id string) error {
	_, err := d.Ctx(ctx).WherePri(id).Update(map[string]interface{}{
		d.Columns().DeletedAt: gtime.Now(),
	})
	return err
}

func (d *ydstermHostsDao) Get(ctx context.Context, id string) (*entity.YdstermHosts, error) {
	var host *entity.YdstermHosts
	err := d.Ctx(ctx).WherePri(id).Scan(&host)
	return host, err
}

func (d *ydstermHostsDao) List(ctx context.Context, groupID string) ([]entity.YdstermHosts, error) {
	m := d.Ctx(ctx).WhereNull(d.Columns().DeletedAt)
	if groupID != "" {
		m = m.Where(d.Columns().GroupId, groupID)
	}
	var hosts []entity.YdstermHosts
	err := m.OrderAsc(d.Columns().Name).Scan(&hosts)
	if err != nil {
		return nil, err
	}
	if hosts == nil {
		hosts = []entity.YdstermHosts{}
	}
	return hosts, nil
}
