// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ydsterm-server/internal/dao/internal"
)

// syncHostsDao is the data access object for the table sync_hosts.
// You can define custom methods on it to extend its functionality as needed.
type syncHostsDao struct {
	*internal.SyncHostsDao
}

var (
	// SyncHosts is a globally accessible object for table sync_hosts operations.
	SyncHosts = syncHostsDao{internal.NewSyncHostsDao()}
)

// Add your custom methods and functionality below.
