// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ydsterm-server/internal/dao/internal"
)

// syncSnippetsDao is the data access object for the table sync_snippets.
// You can define custom methods on it to extend its functionality as needed.
type syncSnippetsDao struct {
	*internal.SyncSnippetsDao
}

var (
	// SyncSnippets is a globally accessible object for table sync_snippets operations.
	SyncSnippets = syncSnippetsDao{internal.NewSyncSnippetsDao()}
)

// Add your custom methods and functionality below.
