// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ydsterm-server/internal/dao/internal"
)

// syncHostGroupsDao is the data access object for the table sync_host_groups.
// You can define custom methods on it to extend its functionality as needed.
type syncHostGroupsDao struct {
	*internal.SyncHostGroupsDao
}

var (
	// SyncHostGroups is a globally accessible object for table sync_host_groups operations.
	SyncHostGroups = syncHostGroupsDao{internal.NewSyncHostGroupsDao()}
)

// Add your custom methods and functionality below.
