// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ydsterm-server/internal/dao/internal"
)

// syncKeysDao is the data access object for the table sync_keys.
// You can define custom methods on it to extend its functionality as needed.
type syncKeysDao struct {
	*internal.SyncKeysDao
}

var (
	// SyncKeys is a globally accessible object for table sync_keys operations.
	SyncKeys = syncKeysDao{internal.NewSyncKeysDao()}
)

// Add your custom methods and functionality below.
