// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ydsterm-server/internal/dao/internal"
)

// syncPortForwardsDao is the data access object for the table sync_port_forwards.
// You can define custom methods on it to extend its functionality as needed.
type syncPortForwardsDao struct {
	*internal.SyncPortForwardsDao
}

var (
	// SyncPortForwards is a globally accessible object for table sync_port_forwards operations.
	SyncPortForwards = syncPortForwardsDao{internal.NewSyncPortForwardsDao()}
)

// Add your custom methods and functionality below.
