// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ydsterm-server/internal/dao/internal"
)

// syncSnippetFoldersDao is the data access object for the table sync_snippet_folders.
// You can define custom methods on it to extend its functionality as needed.
type syncSnippetFoldersDao struct {
	*internal.SyncSnippetFoldersDao
}

var (
	// SyncSnippetFolders is a globally accessible object for table sync_snippet_folders operations.
	SyncSnippetFolders = syncSnippetFoldersDao{internal.NewSyncSnippetFoldersDao()}
)

// Add your custom methods and functionality below.
