// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ydsterm-server/internal/dao/internal"
)

// syncUsersDao is the data access object for the table sync_users.
// You can define custom methods on it to extend its functionality as needed.
type syncUsersDao struct {
	*internal.SyncUsersDao
}

var (
	// SyncUsers is a globally accessible object for table sync_users operations.
	SyncUsers = syncUsersDao{internal.NewSyncUsersDao()}
)

// Add your custom methods and functionality below.
